//tealium universal tag - x_axis.61 ut4.0.201810250914, Copyright 2018 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={"id":id};x_axis.o[loader].sender[id]=u;if(x_axis.ut===undefined){x_axis.ut={};}
if(x_axis.ut.loader===undefined){u.loader=function(o){var b,c,l,a=document;if(o.type==="iframe"){b=a.createElement("iframe");o.attrs=o.attrs||{"height":"1","width":"1","style":"display:none"};for(l in x_axis.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);}else if(o.type=="img"){x_axis.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";for(l in x_axis.loader.GV(o.attrs)){b[l]=o.attrs[l];}b.src=o.src;}if(o.id){b.id=o.id};if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb()},false);}else{b.onreadystatechange=function(){if(this.readyState=='complete'||this.readyState=='loaded'){this.onreadystatechange=null;o.cb()}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){x_axis.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b)}}}}else{u.loader=x_axis.ut.loader;}
u.encode=function(a,b){b="";try{b=encodeURIComponent(a)}catch(e){x_axis.DB(e);}if(b==""){b=escape(a);}return b}
u.ev={"view":1};u.scriptrequested=false;u.rp=function(a,b){if(typeof a!=="undefined"&&a.indexOf("@@")>0){a=a.replace(/@@([^@]+)@@/g,function(m,d){if(b[d]){return u.encode(b[d]);}else{return"";}});}
return a;};u.map={};u.extend=[function(a,b,c,d,e,f,g){d=b['dom.url'];if(typeof d=='undefined')return;c=[{'https://www.acko.com/?buy=null&advisor=null':'8966601|invmedia|in_ac0'},{'https://www.acko.com/lp/bike/':'8966601|invmedia|in_ac00'},{'https://www.acko.com/login/?next=/ola/':'8966601|invmedia|in_ac000'},{'https://www.acko.com/amazonmobile/protection/':'8966601|invmedia|in_ac001'},{'https://www.acko.com/amazonmobile/screenprotection/':'8966601|invmedia|in_ac002'},{'https://www.acko.com/motor-claims/':'8966601|invmedia|in_ac003'},{'https://www.acko.com/bike-claims/':'8966601|invmedia|in_ac004'},{'https://www.acko.com/login/?next=/ola/':'8966601|invmedia|in_ac005'},{'https://www.acko.com/amazonmobile/claim/':'8966601|invmedia|in_ac006'},{'https://www.acko.com/login/?next=/home2/':'8966601|invmedia|in_ac007'},{'https://www.acko.com/articles/car-insurance/':'8966601|invmedia|in_ac008'},{'https://www.acko.com/articles/two-wheeler-insurance/':'8966601|invmedia|in_ac009'},{'https://www.acko.com/articles/travel-insurance/':'8966601|invmedia|in_ac00-'},{'https://www.acko.com/articles/health-insurance/':'8966601|invmedia|in_ac00a'},{'https://www.acko.com/articles/driving-license/':'8966601|invmedia|in_ac00b'},{'https://www.acko.com/articles/rto/':'8966601|invmedia|in_ac00c'},{'https://www.acko.com/articles/traffic-rules-violations/':'8966601|invmedia|in_ac00d'},{'https://www.acko.com/articles/general-info/':'8966601|invmedia|in_ac00e'},{'https://www.acko.com/mmv/?':'8966601|invmedia|in_ac00f'},{'https://www.acko.com/buy-renew-car-insurance-online/#/':'8966601|invmedia|in_ac00g'},{'https://www.acko.com/lp/thirdparty/':'8966601|invmedia|in_ac00h'}];var m=false;for(e=0;e<c.length;e++){for(f in c[e]){if(d.toString().indexOf(f)>-1){b['dc_temp']=c[e][f];m=true};};if(m)break};},function(a,b){try{if((typeof b['dc_temp']!='undefined'&&typeof b['dc_temp']!='undefined'&&b['dc_temp']!='')){try{b['dc_src']=b['dc_temp'].split('|')[0]}catch(e){};try{b['dc_type']=b['dc_temp'].split('|')[1]}catch(e){};try{b['dc_cat']=b['dc_temp'].split('|')[2]}catch(e){}}}catch(e){x_axis.DB(e)}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f;u.data={"qsp_delim":"&"||"&","kvp_delim":"="||"=","qs_delim":"?"||"?","tag_type":"img","base_url":"//ad.doubleclick.net/ddm/activity/src=@@dc_src@@;type=@@dc_type@@;cat=@@dc_cat@@;dc_lat=;dc_rdid=;tag_for_child_directed_treatment=;tfua=;npa=;ord=@@cache_bust@@?","secure_base_url":"","static_params":"","cachebust":"disabled","cachevar":""||"_rnd","requestscriptonce":"disabled"};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};x_axis.DB("send:61:EXTENSIONS");x_axis.DB(b);c=[];for(d in x_axis.loader.GV(u.map)){if(typeof b[d]!=="undefined"&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){if(!u.data.hasOwnProperty(e[f])){c.push(e[f]+"##kvp_delim##"+u.encode(b[d]));}
u.data[e[f]]=b[d];}}}
if(!u.data.base_url){if(!u.data.secure_base_url){x_axis.DB("Error: No Base URL or Secure HTTPS Override Provided.");return;}else{u.data.base_url=u.data.secure_base_url;x_axis.DB("No Base URL provided, using Secure HTTPS Override.");}}
u.data.secure_base_url=u.data.secure_base_url||u.data.base_url;u.data.url=(location.protocol==="https:"?u.data.secure_base_url:u.data.base_url);if(u.data.url.indexOf("http")!==0&&u.data.url.indexOf("/")!==0){u.data.url=location.protocol+"//"+u.data.url;}
if(u.data.static_params){c.push(u.data.static_params);}
var cb_check=new RegExp("(\\"+u.data.qs_delim+"|"+u.data.qsp_delim+")"+u.data.cachevar+"=");if(u.data.cachebust==="enabled"&&!cb_check.test(u.data.url)){c.push([u.data.cachevar,Math.random()].join(u.data.kvp_delim));}
if(c.length>0){if(u.data.url.indexOf(u.data.qs_delim)<0){u.data.url+=u.data.qs_delim;}else if(u.data.url.indexOf(u.data.qs_delim)!==(u.data.url.length-1)){u.data.url+=u.data.qsp_delim;}}
u.data.url=u.rp(u.data.url,b)+u.rp(c.join(u.data.qsp_delim),b);u.data.url=u.data.url.replace(/##kvp_delim##/g,u.data.kvp_delim);u.callback=u.callback||function(){};if(u.data.requestscriptonce==="enabled"&&u.data.tag_type==="script"){if(!u.scriptrequested){u.scriptrequested=true;u.loader({"type":u.data.tag_type,"src":u.data.url,"loc":"script","id":"x_axis_61","cb":u.callback});}else{u.callback();}}else{u.loader({"type":u.data.tag_type,"src":u.data.url,"loc":"script","id":"x_axis_61","cb":u.callback});}
x_axis.DB("send:61:COMPLETE");}};x_axis.o[loader].loader.LOAD(id);}("61","xaxis.-acko"));}catch(error){x_axis.DB(error);}
